service: teamsBotLambda

provider:
  name: aws
  runtime: nodejs10.x
  profile: bot-dev

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
        - 'sns:GetTopicAttributes'
      Resource:
        - !Ref clientTeamsEvents

  environment:
    # AWS configuration
    ACCESS_KEY_ID: FAKE_ACCESS_KEY_ID
    SECRET_ACCESS_KEY: FAKE_SECRET_ACCESS_KEY
    REGION: FAKE_REGION
    DYNAMODB_ENDPOINT: http://localhost:8000

    # Client Teams bot configuration
    APP_ID: 8c08f8e1-f1a3-4076-87e3-51ba152233c9
    APP_PASSWORD: 'hWB.hbn/JZS3i0N2m./rU7RPu5Y1iuvT'

    # Central TC Lambda URI
    CENTRAL_LAMBDA_URI: 'http://localhost:3000'

    # SNS Configuration
    SNS_ENDPOINT: http://localhost:4002 # local development only
    SNS_REGION: ${self:custom.region}
    SNS_ACCOUNT_ID: 123456789012

    # SNS Topics
    CLIENT_TEAMS_EVENTS_TOPIC: ${self:custom.sns.clientTeamsEvents}

functions:
  client_teams_events:
    handler: src/functions/receiver/events.handler
    description: Handles ms teams events
    events:
      - http:
          path: teams/events
          method: post

  events:
    handler: src/functions/events.handler
    description: Handles ms teams events
    events:
      - sns:
          arn: !Ref clientTeamsEvents
          topicName: ${self:custom.sns.clientTeamsEvents}

  response:
    handler: src/functions/response.handler
    description: Handles project response
    events:
      - http:
          path: response
          method: post

  approve:
    handler: src/functions/approve.handler
    description: Receives project approve
    events:
      - http:
          path: approve
          method: post

plugins:
  - serverless-offline
  - serverless-offline-sns

custom:
  serverless-offline:
    port: 3002

  serverless-offline-sns:
    port: 4002
    debug: false

  sns:
    clientTeamsEvents: client-teams-events

  region: ${opt:region, self:provider.region}

resources:
  Resources:
    clientTeamsEvents:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.sns.clientTeamsEvents}
